version: "3.1"

networks:
  nexamerchant-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

services:
  nexamerchant-php-apache:
    image: nicesteven/nexamerchant:latest
    ports:
      - 80:80
    depends_on:
      - nexamerchant-mysql
      - nexamerchant-redis
      - nexamerchant-elasticsearch
      - nexamerchant-mailhog
    volumes:
      - ./.configs/.env:/var/www/html/NexaMerchant/.env
      - ./.configs/.htaccess:/var/www/html/NexaMerchant/public/.htaccess
    networks:
      nexamerchant-network:
        ipv4_address: 172.16.238.10

  nexamerchant-mysql:
    image: mysql:8.0
    #image: percona-server:8.0.34-26
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nexamerchant
      MYSQL_USER: nexamerchant
      MYSQL_PASSWORD: nexamerchant
    expose:
      - 3306
    volumes:
      - ./.configs/mysql-data:/var/lib/mysql/
    networks:
      nexamerchant-network:
        ipv4_address: 172.16.238.11

  nexamerchant-redis:
    image: redis:6.2-alpine
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.configs/redis-data:/data
    networks:
      nexamerchant-network:
        ipv4_address: 172.16.238.12

  nexamerchant-phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: nexamerchant-mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M
    ports:
      - 8080:80
    depends_on:
      - nexamerchant-mysql
    networks:
      nexamerchant-network:
        ipv4_address: 172.16.238.13

  nexamerchant-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./.configs/elasticsearch-data:/var/lib/elasticsearch/data
    expose:
      - 9200
      - 9300
    networks:
      nexamerchant-network:
        ipv4_address: 172.16.238.14

  nexamerchant-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://nexamerchant-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - nexamerchant-elasticsearch
    networks:
      nexamerchant-network:
        ipv4_address: 172.16.238.15

  nexamerchant-mailhog:
    image: mailhog/mailhog
    logging:
        # Disable saving logs.
        driver: 'none'
    expose:
        - 1025
        - 8025
    networks:
      nexamerchant-network:
        ipv4_address: 172.16.238.16